name: build

on:
  push:
    branches:
      - master
      - development
  pull_request:

jobs:
  build:
    name: Build

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.runs-on }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and build source
      run: npm ci

    - name: Test project
      run: npm test -- --watchAll=false

    - name: Lint project
      run: npm run lint
